# Generated by Django 4.2.20 on 2025-04-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OurProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("announcement", models.TextField(verbose_name="Анонс")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        upload_to="our_projects/", verbose_name="Фотография"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=1, verbose_name="Сортировка"),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
                "db_table": "Our_Projects",
            },
        ),
    ]
