# Generated by Django 4.2.20 on 2025-06-18 23:35

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('our_projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurProject2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Символьный код')),
                ('announcement', models.TextField(verbose_name='Анонс')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='our_projects/', verbose_name='Фотография')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Сортировка')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OurProject2Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='our_projects.ourproject2')),
            ],
            options={
                'verbose_name': 'our project2 Translation',
                'db_table': 'our_projects_ourproject2_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
