# Generated by Django 4.2.20 on 2025-04-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("our_projects", "0002_add_announcement_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ourproject",
            name="announcement",
            field=models.TextField(default=None, verbose_name="Анонс"),
            preserve_default=False,
        ),
    ]
