# Generated by Django 4.2.20 on 2025-06-19 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('our_projects', '0002_ourproject2_ourproject2translation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ourproject2translation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ourproject2translation',
            name='master',
        ),
        migrations.DeleteModel(
            name='OurProject2',
        ),
        migrations.DeleteModel(
            name='OurProject2Translation',
        ),
    ]
