# Generated by Django 4.2.20 on 2025-04-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("our_projects", "0003_alter_ourproject_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="ourproject",
            name="slug",
            field=models.SlugField(
                blank=True, unique=True, verbose_name="Символьный код"
            ),
        ),
    ]
