# Generated by Django 4.2.20 on 2025-07-12 18:22

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('our_projects', '0003_alter_ourproject2translation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourproject',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст'),
        ),
    ]
