# Generated by Django 4.2.20 on 2025-07-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.PositiveBigIntegerField(unique=True)),
                ('chat_id', models.BigIntegerField()),
                ('text', models.TextField(blank=True)),
                ('photo_id', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
