# Generated by Django 4.2.20 on 2025-08-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(db_index=True, max_length=255)),
                ('post_id', models.BigIntegerField(db_index=True)),
                ('text', models.TextField()),
                ('post_url', models.URLField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='telegram_posts/')),
                ('photo_url', models.URLField(blank=True)),
                ('photo_source_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('channel', 'post_id')},
            },
        ),
    ]
