# Generated by Django 4.2.20 on 2025-08-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegrampost',
            options={},
        ),
        migrations.RemoveField(
            model_name='telegrampost',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='telegrampost',
            name='date',
        ),
        migrations.RemoveField(
            model_name='telegrampost',
            name='message_id',
        ),
        migrations.RemoveField(
            model_name='telegrampost',
            name='photo_id',
        ),
        migrations.AddField(
            model_name='telegrampost',
            name='channel',
            field=models.CharField(db_index=True, default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegrampost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegrampost',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegrampost',
            name='post_url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telegrampost',
            name='text',
            field=models.TextField(),
        ),
    ]
