# Generated by Django 4.2.20 on 2025-08-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_feed', '0002_alter_telegrampost_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegrampost',
            old_name='photo_url',
            new_name='photo_source_url',
        ),
        migrations.AddField(
            model_name='telegrampost',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='telegram_posts/'),
        ),
    ]
