# Generated by Django 4.2.20 on 2025-08-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_feed', '0003_rename_photo_url_telegrampost_photo_source_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrampost',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
