# Generated by Django 4.2.20 on 2025-08-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_feed', '0004_telegrampost_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrampost',
            name='post_id',
            field=models.BigIntegerField(db_index=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='telegrampost',
            unique_together={('channel', 'post_id')},
        ),
    ]
