# Generated by Django 4.2.20 on 2025-07-08 13:28

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_title', models.CharField(max_length=255, verbose_name='Заголовок в меню')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст')),
                ('order', models.PositiveSmallIntegerField(default=10, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
    ]
