import type { Metadata } from "next";
import { Header } from "@/widgets/header";
import { NextIntlClientProvider } from 'next-intl';
import { cookies as getCookies} from 'next/headers';

import "@styles/colors.css";
import "@styles/fonts.css";
import "@styles/global.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = getCookies();
  const locale = (await cookieStore).get('NEXT_LOCALE')?.value || 'ru';

  return (
    <html lang={locale}>
      <NextIntlClientProvider>
        <body>
          <Header />
          {children}
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
