# Generated by Django 4.2.20 on 2025-07-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_form', '0002_feedbackform_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата отклика'),
        ),
    ]
