# Generated by Django 4.2.20 on 2025-08-30 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('working_time', models.TextField(blank=True, verbose_name='Время работы')),
            ],
            options={
                'verbose_name': 'Контакты сайта',
            },
        ),
        migrations.CreateModel(
            name='PhonesContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='contacts.sitecontacts')),
            ],
        ),
    ]
