# Generated by Django 4.2.20 on 2025-07-12 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecontacts',
            name='phone',
        ),
        migrations.CreateModel(
            name='PhonesContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.sitecontacts')),
            ],
        ),
    ]
