# Generated by Django 4.2.20 on 2025-07-12 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_sitecontacts_phone_phonescontacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonescontacts',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='contacts.sitecontacts'),
        ),
    ]
