# Generated by Django 4.2.20 on 2025-06-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partners",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "image",
                    models.ImageField(upload_to="partners/", verbose_name="Фотография"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Сортировка"
                    ),
                ),
            ],
            options={
                "verbose_name": "Компания партнер",
                "verbose_name_plural": "Компании партнеры",
                "db_table": "Галерея партнеров",
            },
        ),
    ]
