# Generated by Django 4.2.20 on 2025-04-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partners",
            options={
                "verbose_name": "Компания партнер",
                "verbose_name_plural": "Компании партнеры",
            },
        ),
    ]
