# Generated by Django 4.2.20 on 2025-07-12 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='society',
            options={'verbose_name': 'Общество', 'verbose_name_plural': 'Общество'},
        ),
    ]
