# Generated by Django 4.2.20 on 2025-08-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media-library')),
            ],
            options={
                'verbose_name': 'Медиатека',
                'verbose_name_plural': 'Медиатека',
            },
        ),
    ]
