# Generated by Django 4.2.20 on 2025-07-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medialibrary',
            name='image',
            field=models.ImageField(upload_to='media-library'),
        ),
    ]
