# Generated by Django 4.2.20 on 2025-08-30 11:21

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateAwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Символьный код')),
                ('image', models.ImageField(upload_to='awards_candidate/%Y/%m/%d/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Премия',
                'verbose_name_plural': 'Премия',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='candidates', verbose_name='Фото')),
                ('number_of_votes', models.IntegerField(default=0, verbose_name='Количество голосов')),
                ('awards', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='awards_candidate.candidateawards')),
            ],
            options={
                'verbose_name': 'Кандидат',
                'verbose_name_plural': 'Кандидаты',
            },
        ),
        migrations.CreateModel(
            name='CandidateAwardsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='awards_candidate.candidateawards')),
            ],
            options={
                'verbose_name': 'Премия Translation',
                'db_table': 'awards_candidate_candidateawards_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
