# Generated by Django 4.2.20 on 2025-08-01 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards_candidate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateawards',
            old_name='photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='candidateawardstranslation',
            old_name='title',
            new_name='name',
        ),
    ]
