# Generated by Django 4.2.20 on 2025-07-17 04:34

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsOnMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Символьный код')),
                ('announcement', models.TextField(verbose_name='Анонс')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='our_projects/', verbose_name='Фотография')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Новости на главной',
                'verbose_name_plural': 'Новости на главной',
            },
        ),
    ]
