# Generated by Django 4.2.20 on 2025-06-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Congresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_title', models.CharField(max_length=255, verbose_name='Заголовок в меню')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
            ],
        ),
        migrations.CreateModel(
            name='TypeCongresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
