# Generated by Django 4.2.20 on 2025-06-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congresses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypeCongresses',
        ),
        migrations.AlterModelOptions(
            name='congresses',
            options={'verbose_name': 'Съезд', 'verbose_name_plural': 'Съезды'},
        ),
        migrations.AddField(
            model_name='congresses',
            name='order',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
