# Generated by Django 4.2.20 on 2025-06-19 02:23

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('congresses', '0002_delete_typecongresses_alter_congresses_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='congresses',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(default=None, verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
