# Generated by Django 4.2.20 on 2025-06-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congresses', '0003_congresses_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congresses',
            name='order',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Сортировка'),
        ),
    ]
