# Generated by Django 4.2.20 on 2025-06-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedocument',
            name='order',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
