# Generated by Django 4.2.20 on 2025-06-19 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_typedocument_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документы', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='typedocument',
            options={'verbose_name': 'Тип документов', 'verbose_name_plural': 'Типы документов'},
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.typedocument', verbose_name='Документы'),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='order',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
