name: 🚀 Deploy to VPS

on:
  push:
    branches:
      - main  # изменишь, если у тебя другая ветка

jobs:
  deploy:
    name: 🔄 Автодеплой на сервер
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Клонируем репозиторий
        uses: actions/checkout@v3

      - name: 🔐 Подключаемся по SSH и деплоим
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            if [ ! -d "/root/LezgianWebsite" ]; then
              cd /root
              git clone https://Topando:${{ secrets.GH_DEPLOY_TOKEN }}@github.com/Topando/LezgianWebsite.git
            fi
            cd /root/LezgianWebsite
            git pull origin main
            docker-compose -f docker-compose.prod.yml pull
            docker-compose -f docker-compose.prod.yml up -d --build